"""Modify Schema

Revision ID: d39caca1ccb7
Revises: 
Create Date: 2025-08-05 12:11:05.083044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39caca1ccb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tester_age_group', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('tester_gender', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('tester_education', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('tester_vision_status', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('tester_injury_age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tester_braille_ability', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('tester_mobility_ability', sa.String(length=20), nullable=False))
        batch_op.drop_column('tester_age')
        batch_op.drop_column('tester_handedness')
        batch_op.drop_column('tester_visual_acuity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tester_visual_acuity', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tester_handedness', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tester_age', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('tester_mobility_ability')
        batch_op.drop_column('tester_braille_ability')
        batch_op.drop_column('tester_injury_age')
        batch_op.drop_column('tester_vision_status')
        batch_op.drop_column('tester_education')
        batch_op.drop_column('tester_gender')
        batch_op.drop_column('tester_age_group')

    # ### end Alembic commands ###
